---
#node service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    appName: elasticsearch
spec:
  selector:
    appName: elasticsearch
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
#node deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    matchLabels:
      appName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        appName: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: index.docker.io/elasticsearch:2.4
        ports:
        - containerPort: 8080
        env:
        - name: GET_HOSTS_FROM
          value: dns

