---
#node service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    appName: mysql
spec:
  selector:
    appName: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
#node deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      appName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        appName: mysql
    spec:
      containers:
      - name: mysql
        image: index.docker.io/mysql:5.6.32
        ports:
        - containerPort: 3306
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MYSQL_DATABASE
          value: 'my_db'
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MYSQL_USER
          value: 'user'
        - name: MYSQL_PASSWORD
          value: 'runner'
        - name: MYSQL_ROOT_PASSWORD
          value: 'runner'